FROM gradle:8.7-jdk21-alpine AS builder
WORKDIR /workspace

COPY --chown=gradle:gradle build.gradle .
COPY --chown=gradle:gradle settings.gradle .

RUN --mount=type=cache,id=gradle-user-home,target=/home/gradle/.gradle \
    --mount=type=cache,id=gradle-caches,target=/home/gradle/.gradle/caches \
    gradle --no-daemon assemble -x test

COPY --chown=gradle:gradle src src

RUN --mount=type=cache,id=gradle-user-home,target=/home/gradle/.gradle \
    --mount=type=cache,id=gradle-caches,target=/home/gradle/.gradle/caches \
    gradle --no-daemon build

FROM eclipse-temurin:21-jre-alpine


RUN addgroup -S spring && adduser -S spring -G spring

WORKDIR /app

COPY --from=builder /workspace/build/libs/*.jar app.jar


USER spring:spring


EXPOSE 8080

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
